### Softmax

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn.functional as F

z = torch.FloatTensor([1, 2, 3])
hypothesis = F.softmax(z, dim=0)

print(hypothesis)

def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

x = np.array([1.0, 2.0, 3.0])
y = softmax(x)

print(y)

plt.pie(y, labels=y)
plt.show()

tensor([0.0900, 0.2447, 0.6652])
[0.09003057 0.24472847 0.66524096]


<Figure size 640x480 with 1 Axes>

In [3]:
import tensorflow as tf
# tf.set_random_seed(777)

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

X = tf.placeholder(tf.float32, [None, 4])
Y = tf.placeholder(tf.float32, [None, 3])
nb_classes = 3

# Y_one_hot = tf.one_hot(Y, nb_classes)  # one hot
# print("one_hot:", Y_one_hot)
# Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
# print("reshape one_hot:", Y_one_hot)
'''
one_hot: Tensor("one_hot:0", shape=(?, 3, 3), dtype=float32)
reshape one_hot: Tensor("Reshape:0", shape=(?, 3), dtype=float32)
'''


W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits, labels=Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
            _, cost_val = sess.run([optimizer, cost], feed_dict={X: x_data, Y: y_data})

            if step % 500 == 0:
                print(step, cost_val)

    print('--------------')
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))


0 5.3168488
500 0.5216423
1000 0.29899627
1500 0.20769815
2000 0.16978627
--------------
[[1.5235145e-01 8.4763914e-01 9.3735516e-06]] [1]
--------------
[[0.42844313 0.5145136  0.0570433 ]] [1]
--------------
[[1.8035951e-08 4.3145358e-04 9.9956852e-01]] [2]
--------------
[[1.5235154e-01 8.4763902e-01 9.3735507e-06]
 [4.2844296e-01 5.1451373e-01 5.7043299e-02]
 [1.8035951e-08 4.3145337e-04 9.9956852e-01]] [1 1 2]
